spring.application.name=meydan

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/meydanprime}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:3698741}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:dunyaxainefelekzalimeduvardaelekmiolurelkizimelekmiolur}
jwt.expiration=${JWT_EXPIRATION:86400000}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

app.admin.mail=${ADMIN_MAIL:admin@meydan.com}
app.admin.password=${ADMIN_PASSWORD:123}